(()=>{'use strict';
const $=id=>document.getElementById(id);
let normalExpr='',normalDone=false;
const fmt=n=>Number.isInteger(n)?String(n):String(Number(n.toFixed(10)));
function evalNormal(s){const x=s.replaceAll('×','*').replaceAll('÷','/').replaceAll('−','-').replaceAll('%','/100');if(!x||!/^[0-9+\-*/().\s]+$/.test(x))throw Error('invalid');const v=Function('"use strict";return ('+x+')')();if(!Number.isFinite(v))throw Error('invalid');return v}
function renderNormal(){const e=$('expr'),p=$('preview');e.textContent=normalExpr||'0';try{p.textContent=normalExpr?'= '+fmt(evalNormal(normalExpr)):''}catch{p.textContent=''}}
window.N={input(v){if(normalDone){if(!'+-−×÷'.includes(v))normalExpr='';normalDone=false}if('+-−×÷'.includes(v)&&'+-−×÷'.includes(normalExpr.at(-1)))normalExpr=normalExpr.slice(0,-1);normalExpr+=v;renderNormal()},clear(){normalExpr='';normalDone=false;renderNormal()},del(){normalExpr=normalExpr.slice(0,-1);normalDone=false;renderNormal()},percent(){if(/\d$/.test(normalExpr))normalExpr+='%';renderNormal()},paren(){const o=(normalExpr.match(/\(/g)||[]).length,c=(normalExpr.match(/\)/g)||[]).length;normalExpr+=(o>c&&/[\d)]$/.test(normalExpr))?')':(/[\d)%]$/.test(normalExpr)?'×(':'(');renderNormal()},equals(){try{normalExpr=fmt(evalNormal(normalExpr));normalDone=true;renderNormal()}catch{}}};
const OPS=['+','−','×','÷'];let fs={display:'improper',mixed:false,terms:[{w:'',n:'',d:'',op:null}],sel:{i:0,k:'n'},last:null};
function abs(a){return a<0n?-a:a}function gcd(a,b){a=abs(a);b=abs(b);while(b){const t=a%b;a=b;b=t}return a||1n}
function reduce(n,d){if(d===0n)throw Error('zero denominator');if(d<0n){n=-n;d=-d}const g=gcd(n,d);return[n/g,d/g]}
function ratAdd(a,b){return reduce(a[0]*b[1]+b[0]*a[1],a[1]*b[1])}function ratSub(a,b){return reduce(a[0]*b[1]-b[0]*a[1],a[1]*b[1])}function ratMul(a,b){return reduce(a[0]*b[0],a[1]*b[1])}function ratDiv(a,b){if(b[0]===0n)throw Error('division by zero');return reduce(a[0]*b[1],a[1]*b[0])}
function termRat(t){if(t.d==='')return[t.w?BigInt(t.w):0n,1n];const w=t.w?BigInt(t.w):0n,n=t.n?BigInt(t.n):0n,d=BigInt(t.d);const sign=w<0n?-1n:1n;return reduce(w*d+sign*n,d)}
function calc(){let vals=fs.terms.map(termRat),ops=fs.terms.slice(0,-1).map(t=>t.op);for(let i=0;i<ops.length;){if(ops[i]==='×'||ops[i]==='÷'){vals[i]=ops[i]==='×'?ratMul(vals[i],vals[i+1]):ratDiv(vals[i],vals[i+1]);vals.splice(i+1,1);ops.splice(i,1)}else i++}let r=vals[0]||[0n,1n];for(let i=0;i<ops.length;i++)r=ops[i]==='+'?ratAdd(r,vals[i+1]):ratSub(r,vals[i+1]);return r}
function parts(r){let[n,d]=r;if(n===0n)return{w:'0',n:'',d:''};let neg=n<0n;let a=abs(n),w=a/d,rem=a%d;if(rem===0n)return{w:String(neg?-w:w),n:'',d:''};return{w:w?String(neg?-w:w):'',n:String(rem),d:String(d)}}
function decimal(r){let[n,d]=r,neg=n<0n; n=abs(n);let w=n/d,rem=n%d;if(!rem)return(neg?'-':'')+w;let out='',seen=new Set();for(let i=0;rem&&i<30;i++){if(seen.has(rem)){out+='…';break}seen.add(rem);rem*=10n;out+=(rem/d);rem%=d}return(neg?'-':'')+w+'.'+out}
function fracNode(n,d){const s=document.createElement('span');s.className='answer-stack';const a=document.createElement('span');a.className='answer-num';a.textContent=n;const l=document.createElement('span');l.className='answer-line';const b=document.createElement('span');b.className='answer-den';b.textContent=d;s.append(a,l,b);return s}
function resultNode(r){const wrap=document.createElement('div');wrap.className='answer-fraction';const p=parts(r);if(fs.display==='decimal'){const x=document.createElement('span');x.className='answer-decimal';x.textContent=decimal(r);wrap.append(x);return wrap}if(fs.display==='mixed'&&p.w&&p.n){const w=document.createElement('span');w.className='answer-whole';w.textContent=p.w;wrap.append(w,fracNode(p.n,p.d));return wrap}if(p.n){wrap.append(fracNode(String(r[0]),String(r[1])))}else{const w=document.createElement('span');w.className='answer-whole';w.textContent=p.w;wrap.append(w)}return wrap}
function reductionNode(r){const note=$('fractionReduction');note.replaceChildren();const[n,d]=r,g=gcd(n,d);if(n===0n||d===1n||g===1n)return;const old=document.createElement('span');old.className='reduce-old';old.textContent=abs(n)+'/'+d;const fac=document.createElement('sup');fac.textContent=' ÷'+g;const arrow=document.createElement('span');arrow.className='reduce-arrow';arrow.textContent=' → ';const neu=document.createElement('span');neu.className='reduce-new';neu.textContent=abs(n/g)+'/'+(d/g);old.append(fac);note.append(old,arrow,neu)}
function showResult(){const el=$('fractionResult');el.replaceChildren();try{const r=calc();fs.last=r;el.append(resultNode(r));reductionNode(r)}catch{fs.last=null;$('fractionReduction').replaceChildren()}}
function draw(){const root=$('fracs');root.replaceChildren();fs.terms.forEach((t,i)=>{if(i){const o=document.createElement('button');o.type='button';o.className='fraction-operator';o.textContent=t.op||fs.terms[i-1].op||'+';o.onclick=()=>{const j=OPS.indexOf(fs.terms[i-1].op);fs.terms[i-1].op=OPS[(j+1)%OPS.length];draw()};root.append(o)}const f=document.createElement('div');f.className='fraction';if(fs.mixed)f.append(part(i,'w'));const st=document.createElement('div');st.className='stack';st.append(part(i,'n'));const line=document.createElement('div');line.className='num';st.append(line);st.append(part(i,'d'));f.append(st);root.append(f)});showResult()}
function part(i,k){const b=document.createElement('button');b.type='button';b.className='part '+(fs.sel.i===i&&fs.sel.k===k?'selected':'');b.textContent=fs.terms[i][k]||'0';b.onclick=()=>{fs.sel={i,k};draw()};return b}
window.F={digit(v){const p=fs.terms[fs.sel.i];p[fs.sel.k]=(p[fs.sel.k]||'')+v;draw()},del(){const p=fs.terms[fs.sel.i];p[fs.sel.k]=(p[fs.sel.k]||'').slice(0,-1);draw()},op(v){const p=fs.terms[fs.sel.i];if(!p.n&&!p.d&&!p.w)return;p.op=v;if(fs.sel.i===fs.terms.length-1){fs.terms.push({w:'',n:'',d:'',op:null});fs.sel={i:fs.terms.length-1,k:fs.mixed?'w':'n'}}draw()},add(){const p=fs.terms.at(-1);if(!p.n&&!p.d&&!p.w)return;p.op='+';fs.terms.push({w:'',n:'',d:'',op:null});fs.sel={i:fs.terms.length-1,k:fs.mixed?'w':'n'};draw()},remove(){if(fs.terms.length===1)fs.terms=[{w:'',n:'',d:'',op:null}];else{const i=fs.sel.i;fs.terms.splice(i,1);fs.sel={i:Math.max(0,i-1),k:fs.mixed?'w':'n'}}draw()},clear(){fs={display:'improper',mixed:false,terms:[{w:'',n:'',d:'',op:null}],sel:{i:0,k:'n'},last:null};draw()},cycleDisplay(){fs.display=fs.display==='improper'?'mixed':fs.display==='mixed'?'decimal':'improper';showResult()},toggleMixedInput(){fs.mixed=!fs.mixed;fs.sel.k=fs.mixed?'w':'n';draw()},equals(){try{const r=calc();fs.terms=[parts(r)];fs.sel={i:0,k:fs.mixed?'w':'n'};draw()}catch{}}};
renderNormal();draw();
})();